export const evaluationDataset = [
  {
    id: "products-services",
    question: "What products and services does Apple sell?",
    relevantChunkIds: ["finrag-0", "finrag-1", "finrag-2", "finrag-3", "finrag-105", "finrag-136"],
  },
  {
    id: "business-risks",
    question: "What are Apple's main business risks?",
    relevantChunkIds: [
      "finrag-17",
      "finrag-19",
      "finrag-23",
      "finrag-25",
      "finrag-30",
      "finrag-34",
      "finrag-36",
      "finrag-38",
      "finrag-39",
      "finrag-43",
      "finrag-48",
      "finrag-54",
      "finrag-65",
      "finrag-70",
      "finrag-86",
      "finrag-87",
    ],
  },
  {
    id: "net-sales",
    question: "How did net sales change during the reporting period?",
    relevantChunkIds: [
      "finrag-103",
      "finrag-104",
      "finrag-105",
      "finrag-106",
      "finrag-122",
      "finrag-136",
      "finrag-137",
      "finrag-168",
      "finrag-169",
    ],
  },
  {
    id: "research-development",
    question: "What are Apple's research and development expenses?",
    relevantChunkIds: ["finrag-9", "finrag-107", "finrag-108", "finrag-122", "finrag-168", "finrag-169", "finrag-170"],
  },
  {
    id: "competition",
    question: "How does Apple describe competition in its markets?",
    relevantChunkIds: ["finrag-4", "finrag-5", "finrag-6", "finrag-7", "finrag-30"],
  },
  {
    id: "supply-chain",
    question: "What supply chain and component risks does Apple face?",
    relevantChunkIds: ["finrag-7", "finrag-8", "finrag-17", "finrag-25", "finrag-34", "finrag-36", "finrag-166", "finrag-167"],
  },
  {
    id: "human-capital",
    question: "How many employees does Apple have and how does it approach human capital?",
    relevantChunkIds: ["finrag-12", "finrag-13", "finrag-14"],
  },
  {
    id: "revenue-recognition",
    question: "How does Apple recognize revenue for products and services?",
    relevantChunkIds: ["finrag-132", "finrag-133", "finrag-134", "finrag-135", "finrag-136", "finrag-137"],
  },
];
